#!/bin/bash -ex

source /usr/local/src/canvas.conf

# download and set branch to version
URL="https://github.com/instructure/canvas-lms.git"

[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY
git clone $URL $WEBROOT --depth=1 -b stable
unset HTTP_PROXY

cd $WEBROOT
sed -i 's|"yarn": "^1.10.1"|"yarn": "^1.12.3"|' package.json
